import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization") || req.headers.get("authorization");

    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    const adminClient = createClient(supabaseUrl, serviceKey);
    const token = authHeader.replace("Bearer ", "").trim();
    const { data: { user }, error: userError } = await adminClient.auth.getUser(token);

    if (userError || !user) {
      console.error("Auth error:", userError?.message || "No user found");
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const userId = user.id;
    const userEmail = user.email || "unknown";

    // Check roles
    const { data: roles, error: rolesError } = await adminClient
      .from("user_roles")
      .select("role")
      .eq("user_id", userId);

    if (rolesError) {
      return new Response(JSON.stringify({ error: "Erro ao validar permissões" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const userRoles = (roles || []).map((r: { role: string }) => r.role);
    if (!userRoles.includes("admin") && !userRoles.includes("nutritionist")) {
      return new Response(JSON.stringify({ error: "Forbidden" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const lines: string[] = [];
    const stats = { extensions: 0, enums: 0, tables: 0, constraints: 0, indexes: 0, functions: 0, triggers: 0, rls_tables: 0, policies: 0, data_tables: 0 };

    lines.push("-- ══════════════════════════════════════════════════════════════");
    lines.push("-- FitJourney — Complete Restorable SQL Backup");
    lines.push(`-- Generated at: ${new Date().toISOString()}`);
    lines.push(`-- Generated by: ${userEmail}`);
    lines.push("-- Sections: Extensions → Types → Tables → Constraints → Indexes");
    lines.push("--           → Functions → Triggers → RLS → Data");
    lines.push("-- ══════════════════════════════════════════════════════════════");
    lines.push("");
    lines.push("BEGIN;");
    lines.push("");

    // ── 1. EXTENSIONS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 1: EXTENSIONS");
    lines.push("-- ═══════════════════════════════════════");
    const { data: extensions } = await adminClient.rpc("get_backup_extensions");
    if (extensions) {
      for (const ext of extensions) {
        lines.push(`${ext.create_statement};`);
        stats.extensions++;
      }
    }
    lines.push("");

    // ── 2. CUSTOM TYPES / ENUMS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 2: CUSTOM TYPES (ENUMS)");
    lines.push("-- ═══════════════════════════════════════");
    const { data: enums } = await adminClient.rpc("get_backup_enums");
    if (enums) {
      for (const en of enums) {
        lines.push(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '${en.enum_name}') THEN ${en.create_statement}; END IF; END $$;`);
        stats.enums++;
      }
    }
    lines.push("");

    // ── 3. TABLES (structure only, no constraints) ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 3: TABLES");
    lines.push("-- ═══════════════════════════════════════");
    const { data: tables, error: tablesErr } = await adminClient.rpc("get_backup_tables");
    if (tablesErr) {
      console.error("Tables error:", tablesErr.message);
      return new Response(JSON.stringify({ error: `Erro ao buscar tabelas: ${tablesErr.message}` }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (tables) {
      for (const t of tables) {
        lines.push(`CREATE TABLE IF NOT EXISTS public.${quote(t.table_name)} (`);
        // get_backup_tables already returns the column defs inside create_statement
        // Extract column defs from the create_statement
        const match = t.create_statement.match(/\(([\s\S]+)\)/);
        if (match) {
          lines.push(match[1]);
        }
        lines.push(");");
        lines.push("");
        stats.tables++;
      }
    }

    // ── 4. CONSTRAINTS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 4: CONSTRAINTS (PK, FK, UNIQUE, CHECK)");
    lines.push("-- ═══════════════════════════════════════");
    const { data: constraints } = await adminClient.rpc("get_backup_constraints");
    if (constraints) {
      // Group: PK first, then UNIQUE, CHECK, FK last
      for (const c of constraints) {
        lines.push(`DO $$ BEGIN ${c.create_statement}; EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        stats.constraints++;
      }
    }
    lines.push("");

    // ── 5. INDEXES ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 5: INDEXES");
    lines.push("-- ═══════════════════════════════════════");
    const { data: indexes } = await adminClient.rpc("get_backup_indexes");
    if (indexes) {
      for (const idx of indexes) {
        // Replace CREATE INDEX with CREATE INDEX IF NOT EXISTS
        const stmt = idx.create_statement.replace(/^CREATE INDEX/i, "CREATE INDEX IF NOT EXISTS")
          .replace(/^CREATE UNIQUE INDEX/i, "CREATE UNIQUE INDEX IF NOT EXISTS");
        lines.push(`${stmt};`);
        stats.indexes++;
      }
    }
    lines.push("");

    // ── 6. FUNCTIONS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 6: FUNCTIONS & PROCEDURES");
    lines.push("-- ═══════════════════════════════════════");
    const { data: functions } = await adminClient.rpc("get_backup_functions");
    if (functions) {
      for (const fn of functions) {
        // pg_get_functiondef returns CREATE OR REPLACE already
        lines.push(`${fn.create_statement};`);
        lines.push("");
        stats.functions++;
      }
    }

    // ── 7. TRIGGERS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 7: TRIGGERS");
    lines.push("-- ═══════════════════════════════════════");
    const { data: triggers } = await adminClient.rpc("get_backup_triggers");
    if (triggers) {
      for (const tr of triggers) {
        lines.push(`DROP TRIGGER IF EXISTS ${quote(tr.trigger_name)} ON public.${quote(tr.table_name)};`);
        lines.push(`${tr.create_statement};`);
        lines.push("");
        stats.triggers++;
      }
    }

    // ── 8. RLS ENABLE + POLICIES ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 8: ROW LEVEL SECURITY");
    lines.push("-- ═══════════════════════════════════════");

    const { data: rlsTables } = await adminClient.rpc("get_backup_rls_enabled");
    if (rlsTables) {
      for (const rls of rlsTables) {
        lines.push(`${rls.rls_statement};`);
        stats.rls_tables++;
      }
    }
    lines.push("");

    lines.push("-- ─── RLS Policies ───");
    const { data: policies } = await adminClient.rpc("get_backup_rls_policies");
    if (policies) {
      for (const pol of policies) {
        lines.push(`DROP POLICY IF EXISTS ${quote(pol.policy_name)} ON public.${quote(pol.table_name)};`);
        lines.push(`${pol.create_statement};`);
        lines.push("");
        stats.policies++;
      }
    }

    // ── 9. SEED DATA ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 9: DATA (INSERT STATEMENTS)");
    lines.push("-- ═══════════════════════════════════════");

    if (tables) {
      for (const tableInfo of tables) {
        const tableName = tableInfo.table_name;

        // Fetch data in pages to handle large tables
        let offset = 0;
        const pageSize = 5000;
        let hasData = false;

        while (true) {
          const { data: rows, error: dataErr } = await adminClient
            .from(tableName)
            .select("*")
            .range(offset, offset + pageSize - 1);

          if (dataErr || !rows || rows.length === 0) break;

          if (!hasData) {
            lines.push(`-- ─── Data: ${tableName} ───`);
            hasData = true;
          }

          const columns = Object.keys(rows[0]);
          const colList = columns.map((c) => quote(c)).join(", ");

          for (let i = 0; i < rows.length; i += 100) {
            const batch = rows.slice(i, i + 100);
            lines.push(`INSERT INTO public.${quote(tableName)} (${colList}) VALUES`);
            const valueLines = batch.map((row) => {
              const values = columns.map((col) => {
                const val = row[col];
                if (val === null || val === undefined) return "NULL";
                if (typeof val === "number") return String(val);
                if (typeof val === "boolean") return val ? "TRUE" : "FALSE";
                if (typeof val === "object") {
                  return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
                }
                return `'${String(val).replace(/'/g, "''")}'`;
              });
              return `  (${values.join(", ")})`;
            });
            lines.push(`${valueLines.join(",\n")}`);
            lines.push("ON CONFLICT DO NOTHING;");
            lines.push("");
          }

          if (rows.length < pageSize) break;
          offset += pageSize;
        }

        if (hasData) {
          stats.data_tables++;
        }
      }
    }

    // ── SUMMARY ──
    lines.push("");
    lines.push("COMMIT;");
    lines.push("");
    lines.push("-- ══════════════════════════════════════════════════════════════");
    lines.push("-- BACKUP SUMMARY");
    lines.push("-- ══════════════════════════════════════════════════════════════");
    lines.push(`-- Extensions:      ${stats.extensions}`);
    lines.push(`-- Custom Types:    ${stats.enums}`);
    lines.push(`-- Tables:          ${stats.tables}`);
    lines.push(`-- Constraints:     ${stats.constraints}`);
    lines.push(`-- Indexes:         ${stats.indexes}`);
    lines.push(`-- Functions:       ${stats.functions}`);
    lines.push(`-- Triggers:        ${stats.triggers}`);
    lines.push(`-- RLS Tables:      ${stats.rls_tables}`);
    lines.push(`-- RLS Policies:    ${stats.policies}`);
    lines.push(`-- Tables w/ data:  ${stats.data_tables}`);
    lines.push("-- ══════════════════════════════════════════════════════════════");

    return new Response(lines.join("\n"), {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/sql",
        "Content-Disposition": `attachment; filename="fitjourney_full_backup_${new Date().toISOString().slice(0, 10)}.sql"`,
      },
    });
  } catch (error) {
    console.error("Backup error:", error);
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Erro interno" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

function quote(identifier: string): string {
  return `"${identifier}"`;
}
