import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization") || req.headers.get("authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const adminClient = createClient(supabaseUrl, serviceKey);
    const token = authHeader.replace("Bearer ", "").trim();
    const { data: { user }, error: userError } = await adminClient.auth.getUser(token);

    if (userError || !user) {
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const userId = user.id;
    const userEmail = user.email || "unknown";

    const { data: roles, error: rolesError } = await adminClient
      .from("user_roles")
      .select("role")
      .eq("user_id", userId);

    if (rolesError) {
      return new Response(JSON.stringify({ error: "Erro ao validar permissões" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const userRoles = (roles || []).map((r: { role: string }) => r.role);
    if (!userRoles.includes("admin") && !userRoles.includes("nutritionist")) {
      return new Response(JSON.stringify({ error: "Forbidden" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const lines: string[] = [];
    const stats = { extensions: 0, enums: 0, tables: 0, constraints: 0, indexes: 0, functions: 0, triggers: 0, rls_tables: 0, policies: 0, views: 0, data_tables: 0 };
    const warnings: string[] = [];

    lines.push("-- ══════════════════════════════════════════════════════════════");
    lines.push("-- FitJourney — Complete Restorable SQL Backup");
    lines.push(`-- Generated at: ${new Date().toISOString()}`);
    lines.push(`-- Generated by: ${userEmail}`);
    lines.push("-- Sections: Extensions → Types → Tables → Constraints → Indexes");
    lines.push("--           → Functions → Triggers → Views → RLS → Data → Validation");
    lines.push("-- ══════════════════════════════════════════════════════════════");
    lines.push("");
    lines.push("BEGIN;");
    lines.push("");

    // Helper to call RPC with error handling
    async function rpc<T>(name: string): Promise<T[]> {
      const { data, error } = await adminClient.rpc(name);
      if (error) {
        const msg = `RPC ${name} failed: ${error.message}`;
        console.error(msg);
        warnings.push(msg);
        return [];
      }
      return (data || []) as T[];
    }

    // ── 1. EXTENSIONS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 1: EXTENSIONS");
    lines.push("-- ═══════════════════════════════════════");
    const extensions = await rpc<{ create_statement: string }>("get_backup_extensions");
    for (const ext of extensions) {
      lines.push(`${ext.create_statement};`);
      stats.extensions++;
    }
    lines.push("");

    // ── 2. CUSTOM TYPES / ENUMS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 2: CUSTOM TYPES (ENUMS)");
    lines.push("-- ═══════════════════════════════════════");
    const enums = await rpc<{ enum_name: string; create_statement: string }>("get_backup_enums");
    for (const en of enums) {
      lines.push(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '${en.enum_name}') THEN ${en.create_statement}; END IF; END $$;`);
      stats.enums++;
    }
    lines.push("");

    // ── 3. TABLES ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 3: TABLES");
    lines.push("-- ═══════════════════════════════════════");
    const tables = await rpc<{ table_name: string; create_statement: string }>("get_backup_tables");
    for (const t of tables) {
      lines.push(`CREATE TABLE IF NOT EXISTS public.${quote(t.table_name)} (`);
      const match = t.create_statement.match(/\(([\s\S]+)\)/);
      if (match) {
        lines.push(match[1]);
      }
      lines.push(");");
      lines.push("");
      stats.tables++;
    }

    // ── 4. CONSTRAINTS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 4: CONSTRAINTS (PK, FK, UNIQUE, CHECK)");
    lines.push("-- ═══════════════════════════════════════");
    const constraints = await rpc<{ create_statement: string }>("get_backup_constraints");
    for (const c of constraints) {
      lines.push(`DO $$ BEGIN ${c.create_statement}; EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
      stats.constraints++;
    }
    lines.push("");

    // ── 5. INDEXES ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 5: INDEXES");
    lines.push("-- ═══════════════════════════════════════");
    const indexes = await rpc<{ create_statement: string }>("get_backup_indexes");
    for (const idx of indexes) {
      const stmt = idx.create_statement
        .replace(/^CREATE INDEX/i, "CREATE INDEX IF NOT EXISTS")
        .replace(/^CREATE UNIQUE INDEX/i, "CREATE UNIQUE INDEX IF NOT EXISTS");
      lines.push(`${stmt};`);
      stats.indexes++;
    }
    lines.push("");

    // ── 6. FUNCTIONS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 6: FUNCTIONS & PROCEDURES");
    lines.push("-- ═══════════════════════════════════════");
    const functions = await rpc<{ create_statement: string }>("get_backup_functions");
    for (const fn of functions) {
      lines.push(`${fn.create_statement};`);
      lines.push("");
      stats.functions++;
    }

    // ── 7. TRIGGERS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 7: TRIGGERS");
    lines.push("-- ═══════════════════════════════════════");
    const triggers = await rpc<{ table_name: string; trigger_name: string; create_statement: string }>("get_backup_triggers");
    for (const tr of triggers) {
      lines.push(`DROP TRIGGER IF EXISTS ${quote(tr.trigger_name)} ON public.${quote(tr.table_name)};`);
      lines.push(`${tr.create_statement};`);
      lines.push("");
      stats.triggers++;
    }

    // ── 8. VIEWS ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 8: VIEWS");
    lines.push("-- ═══════════════════════════════════════");
    const views = await rpc<{ view_name: string; create_statement: string }>("get_backup_views");
    for (const v of views) {
      lines.push(`${v.create_statement};`);
      lines.push("");
      stats.views++;
    }

    // ── 9. RLS ENABLE + POLICIES ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 9: ROW LEVEL SECURITY");
    lines.push("-- ═══════════════════════════════════════");
    const rlsTables = await rpc<{ rls_statement: string }>("get_backup_rls_enabled");
    for (const rls of rlsTables) {
      lines.push(`${rls.rls_statement};`);
      stats.rls_tables++;
    }
    lines.push("");

    lines.push("-- ─── RLS Policies ───");
    const policies = await rpc<{ table_name: string; policy_name: string; create_statement: string }>("get_backup_rls_policies");
    for (const pol of policies) {
      lines.push(`DROP POLICY IF EXISTS ${quote(pol.policy_name)} ON public.${quote(pol.table_name)};`);
      lines.push(`${pol.create_statement};`);
      lines.push("");
      stats.policies++;
    }

    // ── 10. SEED DATA ──
    lines.push("-- ═══════════════════════════════════════");
    lines.push("-- SECTION 10: DATA (INSERT STATEMENTS)");
    lines.push("-- ═══════════════════════════════════════");

    for (const tableInfo of tables) {
      const tableName = tableInfo.table_name;
      let offset = 0;
      const pageSize = 5000;
      let hasData = false;

      while (true) {
        const { data: rows, error: dataErr } = await adminClient
          .from(tableName)
          .select("*")
          .range(offset, offset + pageSize - 1);

        if (dataErr || !rows || rows.length === 0) break;

        if (!hasData) {
          lines.push(`-- ─── Data: ${tableName} ───`);
          hasData = true;
        }

        const columns = Object.keys(rows[0]);
        const colList = columns.map((c) => quote(c)).join(", ");

        for (let i = 0; i < rows.length; i += 100) {
          const batch = rows.slice(i, i + 100);
          lines.push(`INSERT INTO public.${quote(tableName)} (${colList}) VALUES`);
          const valueLines = batch.map((row) => {
            const values = columns.map((col) => {
              const val = row[col];
              if (val === null || val === undefined) return "NULL";
              if (typeof val === "number") return String(val);
              if (typeof val === "boolean") return val ? "TRUE" : "FALSE";
              if (typeof val === "object") {
                return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
              }
              return `'${String(val).replace(/'/g, "''")}'`;
            });
            return `  (${values.join(", ")})`;
          });
          lines.push(`${valueLines.join(",\n")}`);
          lines.push("ON CONFLICT DO NOTHING;");
          lines.push("");
        }

        if (rows.length < pageSize) break;
        offset += pageSize;
      }

      if (hasData) stats.data_tables++;
    }

    lines.push("");
    lines.push("COMMIT;");
    lines.push("");

    // ── VALIDATION ──
    const backupComplete = !(stats.rls_tables > 0 && stats.policies === 0);
    if (!backupComplete) {
      warnings.push(`ATENÇÃO: ${stats.rls_tables} tabelas com RLS habilitado mas 0 policies exportadas. Backup INCOMPLETO para restore.`);
    }

    lines.push("-- ══════════════════════════════════════════════════════════════");
    lines.push("-- BACKUP SUMMARY & VALIDATION REPORT");
    lines.push("-- ══════════════════════════════════════════════════════════════");
    lines.push(`-- Status:          ${backupComplete ? "✅ COMPLETO" : "⚠️ INCOMPLETO"}`);
    lines.push(`-- Extensions:      ${stats.extensions}`);
    lines.push(`-- Custom Types:    ${stats.enums}`);
    lines.push(`-- Tables:          ${stats.tables}`);
    lines.push(`-- Constraints:     ${stats.constraints}`);
    lines.push(`-- Indexes:         ${stats.indexes}`);
    lines.push(`-- Functions:       ${stats.functions}`);
    lines.push(`-- Triggers:        ${stats.triggers}`);
    lines.push(`-- Views:           ${stats.views}`);
    lines.push(`-- RLS Tables:      ${stats.rls_tables}`);
    lines.push(`-- RLS Policies:    ${stats.policies}`);
    lines.push(`-- Tables w/ data:  ${stats.data_tables}`);
    if (warnings.length > 0) {
      lines.push("--");
      lines.push("-- WARNINGS:");
      for (const w of warnings) {
        lines.push(`-- ⚠️  ${w}`);
      }
    }
    lines.push("--");
    lines.push("-- NOTE: Cron jobs (pg_cron) are managed at infrastructure level");
    lines.push("-- and cannot be exported via SQL backup. Document them separately.");
    lines.push("-- ══════════════════════════════════════════════════════════════");

    // Return as JSON with metadata for the client to parse
    const sqlContent = lines.join("\n");
    const responseData = {
      sql: sqlContent,
      stats,
      warnings,
      complete: backupComplete,
    };

    return new Response(JSON.stringify(responseData), {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/json",
      },
    });
  } catch (error) {
    console.error("Backup error:", error);
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Erro interno" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

function quote(identifier: string): string {
  return `"${identifier}"`;
}
