import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceKey);

    // Verify user using the service role client with the user's JWT
    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    
    if (authError || !user) {
      console.error("Auth error:", authError?.message || "No user found");
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    console.log("User authenticated:", user.email);

    // Check if user is admin or nutritionist
    const { data: roles } = await supabase
      .from("user_roles")
      .select("role")
      .eq("user_id", user.id);

    const userRoles = (roles || []).map((r: any) => r.role);
    if (!userRoles.includes("admin") && !userRoles.includes("nutritionist")) {
      return new Response(JSON.stringify({ error: "Forbidden" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    console.log("User roles:", userRoles);

    const lines: string[] = [];
    lines.push("-- =============================================");
    lines.push("-- FitJourney SQL Backup");
    lines.push(`-- Generated at: ${new Date().toISOString()}`);
    lines.push(`-- Generated by: ${user.email}`);
    lines.push("-- =============================================\n");

    // Get all tables in public schema
    const { data: tables, error: rpcError } = await supabase.rpc("get_backup_tables");

    if (rpcError) {
      console.error("RPC error:", rpcError.message);
      return new Response(
        JSON.stringify({ error: "Erro ao buscar tabelas: " + rpcError.message }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!tables || tables.length === 0) {
      return new Response(
        JSON.stringify({ error: "Nenhuma tabela encontrada para backup." }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Found ${tables.length} tables for backup`);

    for (const tableInfo of tables) {
      const tableName = tableInfo.table_name;
      const createStmt = tableInfo.create_statement;

      lines.push(`-- ─── Table: ${tableName} ───`);
      lines.push(`DROP TABLE IF EXISTS public."${tableName}" CASCADE;`);
      lines.push(createStmt + ";\n");

      const { data: rows, error: dataErr } = await supabase
        .from(tableName)
        .select("*")
        .limit(50000);

      if (dataErr || !rows || rows.length === 0) {
        lines.push(`-- No data in ${tableName}\n`);
        continue;
      }

      const columns = Object.keys(rows[0]);
      const colList = columns.map((c) => `"${c}"`).join(", ");

      for (let i = 0; i < rows.length; i += 100) {
        const batch = rows.slice(i, i + 100);
        lines.push(`INSERT INTO public."${tableName}" (${colList}) VALUES`);
        const valueLines = batch.map((row) => {
          const vals = columns.map((col) => {
            const v = row[col];
            if (v === null || v === undefined) return "NULL";
            if (typeof v === "number") return String(v);
            if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
            if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          return `  (${vals.join(", ")})`;
        });
        lines.push(valueLines.join(",\n") + ";\n");
      }
    }

    lines.push("-- ═══ End of backup ═══");

    const sql = lines.join("\n");
    console.log("Backup generated successfully, size:", sql.length);

    return new Response(sql, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/sql",
        "Content-Disposition": `attachment; filename="fitjourney_backup_${new Date().toISOString().slice(0, 10)}.sql"`,
      },
    });
  } catch (err) {
    console.error("Backup error:", err);
    return new Response(
      JSON.stringify({ error: err.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
