DO $$
DECLARE
  v_day_1 jsonb := '{"day_of_week": 1, "meals": [{"id": "m1", "name": "Café da Manhã", "time": "08:00", "items": [{"id": "i1", "kcal": 220, "name": "Ovos Mexidos", "fat": 15, "carbs": 1, "protein": 18, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/pao-com-ovo-tradicional", "quantity": 1, "instanceId": "ins1", "clinical_mass_g": 100, "quantity_display": "2 unidades"}]}, {"id": "m2", "name": "Almoço", "time": "12:00", "items": [{"id": "i2", "kcal": 350, "name": "Frango com Batata Doce", "fat": 8, "carbs": 35, "protein": 35, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/arroz-feijao-frango.png", "quantity": 1, "instanceId": "ins2", "clinical_mass_g": 300, "quantity_display": "300g"}]}]}';
  v_day_2 jsonb := '{"day_of_week": 2, "meals": [{"id": "m3", "name": "Café da Manhã", "time": "08:00", "items": [{"id": "i3", "kcal": 180, "name": "Iogurte com Frutas", "fat": 4, "carbs": 25, "protein": 12, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/iogurte-com-frutas.jpg", "quantity": 1, "instanceId": "ins3", "clinical_mass_g": 200, "quantity_display": "200g"}]}, {"id": "m4", "name": "Almoço", "time": "12:00", "items": [{"id": "i4", "kcal": 420, "name": "Peixe Grelhado com Legumes", "fat": 12, "carbs": 30, "protein": 40, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/tilapia-grelhada.jpg", "quantity": 1, "instanceId": "ins4", "clinical_mass_g": 350, "quantity_display": "350g"}]}]}';
  v_day_3 jsonb := '{"day_of_week": 3, "meals": [{"id": "m5", "name": "Café da Manhã", "time": "08:00", "items": [{"id": "i5", "kcal": 250, "name": "Panqueca de Aveia", "fat": 10, "carbs": 30, "protein": 15, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/mamao-com-aveia.jpg", "quantity": 1, "instanceId": "ins5", "clinical_mass_g": 150, "quantity_display": "150g"}]}, {"id": "m6", "name": "Almoço", "time": "12:00", "items": [{"id": "i6", "kcal": 380, "name": "Carne Moída com Arroz Integral", "fat": 15, "carbs": 40, "protein": 30, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/acem/acem.jpg", "quantity": 1, "instanceId": "ins6", "clinical_mass_g": 300, "quantity_display": "300g"}]}]}';
  v_day_4 jsonb := '{"day_of_week": 4, "meals": [{"id": "m7", "name": "Café da Manhã", "time": "08:00", "items": [{"id": "i7", "kcal": 210, "name": "Torrada com Abacate", "fat": 12, "carbs": 20, "protein": 8, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/abacate.jpg", "quantity": 1, "instanceId": "ins7", "clinical_mass_g": 120, "quantity_display": "120g"}]}, {"id": "m8", "name": "Almoço", "time": "12:00", "items": [{"id": "i8", "kcal": 400, "name": "Strogonoff de Frango Fit", "fat": 18, "carbs": 30, "protein": 35, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/arroz-com-frango.png", "quantity": 1, "instanceId": "ins8", "clinical_mass_g": 320, "quantity_display": "320g"}]}]}';
  v_day_5 jsonb := '{"day_of_week": 5, "meals": [{"id": "m9", "name": "Café da Manhã", "time": "08:00", "items": [{"id": "i9", "kcal": 230, "name": "Crepioca de Queijo", "fat": 12, "carbs": 15, "protein": 16, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/tapioca-com-queijo.jpg", "quantity": 1, "instanceId": "ins9", "clinical_mass_g": 130, "quantity_display": "130g"}]}, {"id": "m10", "name": "Almoço", "time": "12:00", "items": [{"id": "i10", "kcal": 450, "name": "Macarrão Integral com Patinho", "fat": 14, "carbs": 50, "protein": 38, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/maminha-grelhada.jpg", "quantity": 1, "instanceId": "ins10", "clinical_mass_g": 350, "quantity_display": "350g"}]}]}';
  v_day_6 jsonb := '{"day_of_week": 6, "meals": [{"id": "m11", "name": "Café da Manhã", "time": "08:00", "items": [{"id": "i11", "kcal": 190, "name": "Frutas com Granola", "fat": 5, "carbs": 35, "protein": 6, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/abacaxi/abacaxi.jpg", "quantity": 1, "instanceId": "ins11", "clinical_mass_g": 200, "quantity_display": "200g"}]}, {"id": "m12", "name": "Almoço", "time": "12:00", "items": [{"id": "i12", "kcal": 480, "name": "Feijoada Light", "fat": 20, "carbs": 45, "protein": 35, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/feijao-carioca.jpg", "quantity": 1, "instanceId": "ins12", "clinical_mass_g": 400, "quantity_display": "400g"}]}]}';
  v_day_0 jsonb := '{"day_of_week": 0, "meals": [{"id": "m13", "name": "Café da Manhã", "time": "09:00", "items": [{"id": "i13", "kcal": 300, "name": "Brunch Especial", "fat": 18, "carbs": 25, "protein": 20, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/pao-frances.jpg", "quantity": 1, "instanceId": "ins13", "clinical_mass_g": 200, "quantity_display": "200g"}]}, {"id": "m14", "name": "Almoço", "time": "13:00", "items": [{"id": "i14", "kcal": 550, "name": "Lombo Assado com Farofa", "fat": 25, "carbs": 40, "protein": 45, "imageUrl": "https://vkrcobprntictsxqmjjl.supabase.co/storage/v1/object/public/meal-visual-library/lombo-suino/lombo-suino.jpg", "quantity": 1, "instanceId": "ins14", "clinical_mass_g": 400, "quantity_display": "400g"}]}]}';
  v_full_days jsonb := jsonb_build_array(v_day_1, v_day_2, v_day_3, v_day_4, v_day_5, v_day_6, v_day_0);
  v_snapshot jsonb := jsonb_build_object('1600', jsonb_build_object('days', v_full_days), '1800', jsonb_build_object('days', v_full_days));
BEGIN
  -- Aplicar o snapshot 7 dias para todos os templates ativos
  UPDATE v3_diet_templates 
  SET plan_snapshot = v_snapshot, 
      sovereign_validated = true,
      active = true;
      
  -- Garantir que os slugs estejam corretos
  UPDATE v3_diet_templates SET slug = 'bariatrica-solida' WHERE title ILIKE '%Bariátrica%';
  UPDATE v3_diet_templates SET slug = 'low-carb-acessivel' WHERE title ILIKE '%Low Carb%';
  UPDATE v3_diet_templates SET slug = 'emagrecimento-pratico' WHERE title ILIKE '%Emagrecimento%';
  UPDATE v3_diet_templates SET slug = 'hipertrofia-pratica' WHERE title ILIKE '%Hipertrofia%';
  UPDATE v3_diet_templates SET slug = 'colesterol-alto' WHERE title ILIKE '%Colesterol%';
  UPDATE v3_diet_templates SET slug = 'fodmaps-saude-intestinal' WHERE title ILIKE '%FODMAP%';
  UPDATE v3_diet_templates SET slug = 'anti-inflamatorio-premium' WHERE title ILIKE '%Anti-inflamatório%';
  UPDATE v3_diet_templates SET slug = 'ganho-massa-limpa' WHERE title ILIKE '%Ganho de Massa%';
  UPDATE v3_diet_templates SET slug = 'detox-vitalidade' WHERE title ILIKE '%Detox%';
  UPDATE v3_diet_templates SET slug = 'pre-pos-operatorio' WHERE title ILIKE '%Pré e Pós%';
  UPDATE v3_diet_templates SET slug = 'cetogenica-pratica' WHERE title ILIKE '%Cetogênica%';
  UPDATE v3_diet_templates SET slug = 'pratico-rapido-barato' WHERE title ILIKE '%Cardápio Fácil%';
  UPDATE v3_diet_templates SET slug = 'diabetes-controle' WHERE title ILIKE '%Diabetes%';
  UPDATE v3_diet_templates SET slug = 'gestantes-saudavel' WHERE title ILIKE '%Gestantes%';
END $$;