UPDATE public.menu_items SET feature = 'patients' WHERE label = 'Pacientes';
UPDATE public.menu_items SET feature = 'diet' WHERE label = 'Planos Alimentares';
UPDATE public.menu_items SET feature = 'recipes' WHERE label = 'Receitas';
UPDATE public.menu_items SET feature = 'anamnesis' WHERE label = 'Anamnese';
UPDATE public.menu_items SET feature = 'assessment' WHERE label = 'Avaliação Física';
UPDATE public.menu_items SET feature = 'feedback' WHERE label = 'Feedbacks';
UPDATE public.menu_items SET feature = 'consultation' WHERE label = 'Consultas';
UPDATE public.menu_items SET feature = 'appointments' WHERE label = 'Agendamentos';
UPDATE public.menu_items SET feature = 'chat' WHERE label = 'Chat';
UPDATE public.menu_items SET feature = 'reports' WHERE label = 'Relatórios';
UPDATE public.menu_items SET feature = 'analytics' WHERE label = 'Analytics';
UPDATE public.menu_items SET feature = 'protocols' WHERE label = 'Protocolos';
UPDATE public.menu_items SET feature = 'programs' WHERE label = 'Programas';
UPDATE public.menu_items SET feature = 'automation' WHERE label = 'Automação';
UPDATE public.menu_items SET feature = 'branding' WHERE label = 'Branding';
UPDATE public.menu_items SET feature = 'financial' WHERE label = 'Financeiro';
UPDATE public.menu_items SET feature = 'integrations' WHERE label = 'Integrações';
UPDATE public.menu_items SET feature = 'progress' WHERE label = 'Progresso';
UPDATE public.menu_items SET feature = 'tips' WHERE label = 'Dicas';
UPDATE public.menu_items SET feature = 'journey' WHERE label = 'Jornada';
UPDATE public.menu_items SET feature = 'achievements' WHERE label = 'Conquistas';
UPDATE public.menu_items SET feature = 'challenges' WHERE label = 'Desafios';
UPDATE public.menu_items SET feature = 'checklist' WHERE label = 'Checklist';
UPDATE public.menu_items SET feature = 'water-calculator' WHERE label = 'Calculadora Água';
UPDATE public.menu_items SET feature = 'weight-calculator' WHERE label = 'Calculadora Peso';