
-- Limpeza de duplicatas antigas para garantir soberania da nova biblioteca
DELETE FROM diet_templates WHERE template_generation = 'official_v2';

-- [Início dos 40 templates gerados]
INSERT INTO diet_templates (id, name, slug, description, icon, category, goal_category, diet_style, base_calories, macro_ratio, meals, tags, is_active, template_generation, complexity_level, food_access_level) VALUES ('1f45b88a-780e-4c4a-8d85-029315e0ff46', 'Hipertrofia Masculina', 'hipertrofia-masculina-v2', 'Foco em superávit calórico e alta proteína para desenvolvimento muscular masculino.', '💪', 'hipertrofia', 'hipertrofia', 'hipertrofia', 1800, '{"protein": 30, "carbs": 40, "fat": 30}', '[{"meal_type": "breakfast", "title": "Café da Manhã", "blocks": [{"label": "Base", "options": [{"name": "Pão com Ovos", "calories": 330, "protein": 24, "carbs": 25, "fat": 12, "portion": "2 fatias + 2 ovos"}, {"name": "Tapioca Recheada", "calories": 350, "protein": 22, "carbs": 35, "fat": 10, "portion": "1 unidade média"}, {"name": "Cuscuz com Queijo", "calories": 310, "protein": 20, "carbs": 30, "fat": 8, "portion": "1 xícara"}]}]}, {"meal_type": "morning_snack", "title": "Lanche da Manhã", "blocks": [{"label": "Fruta/Iogurte", "options": [{"name": "Fruta da Estação", "calories": 130, "protein": 11, "carbs": 20, "fat": 0, "portion": "1 porção"}, {"name": "Iogurte Natural", "calories": 150, "protein": 17, "carbs": 10, "fat": 4, "portion": "170g"}, {"name": "Mix de Nuts", "calories": 170, "protein": 13, "carbs": 4, "fat": 11, "portion": "20g"}]}]}, {"meal_type": "lunch", "title": "Almoço", "blocks": [{"label": "Prato Principal", "options": [{"name": "Arroz, Feijão e Frango", "calories": 500, "protein": 45, "carbs": 45, "fat": 10, "portion": "1 prato médio"}, {"name": "Macarrão com Carne Moída", "calories": 550, "protein": 40, "carbs": 60, "fat": 15, "portion": "1 prato médio"}, {"name": "Strogonoff de Frango", "calories": 530, "protein": 42, "carbs": 40, "fat": 18, "portion": "1 prato médio"}]}]}, {"meal_type": "afternoon_snack", "title": "Lanche da Tarde", "blocks": [{"label": "Proteico/Prático", "options": [{"name": "Sanduíche de Atum", "calories": 300, "protein": 28, "carbs": 25, "fat": 8, "portion": "1 unidade"}, {"name": "Whey com Banana", "calories": 270, "protein": 35, "carbs": 25, "fat": 2, "short_description": "1 scoop + 1 banana"}]}]}]', ARRAY['premium', 'hipertrofia', 'official'], true, 'official_v2', 'simples', 'facil');
-- [O script acima foi abreviado para demonstração; vou rodar o arquivo SQL gerado via exec se necessário, mas vou tentar o bloco completo aqui]

-- Expansão da meal_library com tags corretas
INSERT INTO meal_library (id, title, meal_type, goal_tag, clinical_tags, base_calories, protein, carbs, fat, foods, is_active)
VALUES
(gen_random_uuid(), 'Costela Suína com Arroz e Mandioca', 'lunch', 'maintenance', ARRAY['performance', 'high_protein'], 650, 45, 40, 35, '[{"name": "Costela Suína Assada", "portion": "150g"}, {"name": "Arroz Branco", "portion": "100g"}, {"name": "Mandioca Cozida", "portion": "80g"}]', true),
(gen_random_uuid(), 'Escondidinho de Carne Moída', 'dinner', 'weight_loss', ARRAY['pratico', 'clean'], 450, 35, 35, 18, '[{"name": "Patinho Moído", "portion": "120g"}, {"name": "Purê de Batata Doce", "portion": "150g"}]', true),
(gen_random_uuid(), 'Arroz Carreteiro Fit', 'lunch', 'maintenance', ARRAY['regional', 'pratico'], 520, 30, 60, 15, '[{"name": "Arroz Integral", "portion": "150g"}, {"name": "Carne Seca Desfiada (Sem Gordura)", "portion": "80g"}]', true),
(gen_random_uuid(), 'Tapioca com Frango e Queijo', 'breakfast', 'maintenance', ARRAY['pratico', 'wellness'], 320, 22, 38, 8, '[{"name": "Goma de Tapioca", "portion": "60g"}, {"name": "Frango Desfiado", "portion": "80g"}]', true),
(gen_random_uuid(), 'Wrap de Frango com Iogurte', 'afternoon_snack', 'weight_loss', ARRAY['pratico', 'low_kcal'], 280, 20, 25, 10, '[{"name": "Tortilha Integral", "portion": "1 unidade"}, {"name": "Frango Grelhado", "portion": "80g"}]', true),
(gen_random_uuid(), 'Strogonoff de Frango Light', 'lunch', 'maintenance', ARRAY['pratico', 'comfort_food'], 480, 40, 35, 20, '[{"name": "Frango em Cubos", "portion": "150g"}, {"name": "Creme de Leite Leve", "portion": "2 colheres"}, {"name": "Arroz", "portion": "100g"}]', true),
(gen_random_uuid(), 'Hambúrguer de Patinho no Prato', 'dinner', 'weight_loss', ARRAY['clean', 'high_protein'], 350, 40, 10, 15, '[{"name": "Hambúrguer de Patinho", "portion": "180g"}, {"name": "Queijo Branco", "portion": "30g"}, {"name": "Salada", "portion": "livre"}]', true),
(gen_random_uuid(), 'Panqueca de Banana e Aveia', 'breakfast', 'maintenance', ARRAY['clean', 'pratico'], 280, 12, 45, 6, '[{"name": "Banana Nanica", "portion": "1 unidade"}, {"name": "Farelo de Aveia", "portion": "30g"}, {"name": "Ovo", "portion": "1 unidade"}]', true),
(gen_random_uuid(), 'Cuscuz Nordestino com Ovos', 'breakfast', 'maintenance', ARRAY['regional', 'wellness'], 310, 15, 40, 12, '[{"name": "Flocão de Milho", "portion": "1 xícara"}, {"name": "Ovo Mexido", "portion": "2 unidades"}]', true);
